spring.application.name=ms-tatabot
server.port=8087

groq.api.key=TU_API_KEY_DE_GROQ
groq.model=openai/gpt-oss-120b
groq.url=https://api.groq.com/openai/v1/chat/completions

ms.logs.url=http://localhost:8081
