server {
    listen 80;

    location / {
        root /media;
        autoindex off;

        # CORS — permite que el frontend acceda a los archivos
        add_header Access-Control-Allow-Origin  *  always;
        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS' always;
        add_header Access-Control-Allow-Headers 'Range, Content-Type' always;
        add_header Access-Control-Expose-Headers 'Content-Range, Accept-Ranges, Content-Length' always;

        # Nginx soporta Range requests nativamente (video seeking)
        # No se necesita configuración extra

        if ($request_method = OPTIONS) {
            return 204;
        }
    }
}
